name: Build docset

on:
  pull_request:
    branches: [ "master" ]
  workflow_call:
    outputs:
      run_id:
        value: ${{ github.run_id }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run script
        run: bash ./scripts/generate_docset.sh

      - uses: actions/upload-artifact@v4
        with:
          name: AWS_CDK_Python.tgz
          path: AWS_CDK_Python.tgz
