name: Build docset

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: run script
        run: bash ./scripts/generate_docset.sh

      - uses: actions/upload-artifact@v3
        with:
          name: AWS_CDK_Python.tgz
          path: AWS_CDK_Python.tgz
