name: Build docset

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: 'macos-latest'
    strategy:
      matrix:
        os:
          - ubuntu-18.04

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - uses: actions/checkout@v3

      - name: run script
        run: bash ./scripts/generate_docset.sh

      - name: docset Verify
        run: |
          wget https://kapeli.com/feeds/zzz/docsetcontrib.tgz; tar -xzf docsetcontrib.tgz;
          ./docsetcontrib --verify | tee output.txt;
          echo output.txt;
          passOrFail=$([ ${PIPESTATUS[0]} == 0  ] && echo "**PASS** 🟢" || echo "**FAIL** 🔴");
          result="$(cat output.txt)";
          result="${result//'%'/%25}";
          result="${result//$'\n'/%0A}";
          result="${result//$'\r'/%0D}";
          echo "::set-output name=result_code::$result";
          echo "::set-output name=passOrFail_code::$passOrFail";
