name: Build release docset

on:
  schedule:
    - cron: '20 10 * * *'
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - id: compare
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          cdkTag=$(gh api /repos/aws/aws-cdk/git/matching-refs/tags/v2. | jq -r 'sort_by(.version) | reverse | .[0].ref | split("/")[-1]')
          echo "cdk=$cdkTag" >> $GITHUB_OUTPUT
          lastestTag=$(gh release view --repo $GITHUB_REPOSITORY --json tagName | jq -r .tagName)

          echo "CDK: $cdkTag"
          echo "This repo: $lastestTag"

          if [[ "${{ github.event_name }}" == "push" ]]
          then
            echo "proceed=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          if [[ "$cdkTag" != "${lastestTag%-*}" ]]
          then
            echo "proceed=true" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "proceed=false" >> $GITHUB_OUTPUT
            exit 0
          fi

    outputs:
      proceed: ${{ steps.compare.outputs.proceed }}
      cdk-version: ${{ steps.compare.outputs.cdk }}

  docset:
    needs: check
    if: ${{ needs.check.outputs.proceed == 'true' }}
    uses: ./.github/workflows/build.yml

  release:
    needs:
      - check
      - docset
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: AWS_CDK_Python.tgz
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          CDK_VERSION: ${{ needs.check.outputs.cdk-version }}
        run: |
          tag="${CDK_VERSION}-$(date +%s)"
          echo "$tag"
          gh release create "$CDK_VERSION-$(date +%s)" ./AWS_CDK_Python.tgz \
            --repo=$GITHUB_REPOSITORY \
            --notes="Release with aws/aws-cdk@$CDK_VERSION" \
            --title="$tag" \
            --latest
